name: Build Pipeline to Azure Function Custom Handler

on:
  [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Build
        run: GOOS=linux go build -o api cmd/api.go
